; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scriptingl
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
;upload_port = COM3
upload_protocol = esptool
upload_speed = 115200
monitor_speed = 115200


; İsteğe bağlı (CDC daha stabil olsun diye)
;build_flags = -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1 -DCORE_DEBUG_LEVEL=3
build_flags =
            -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1 -DCORE_DEBUG_LEVEL=3
            '-DUSB_PRODUCT="Kitronic Tester"'
            '-DUSB_MANUFACTURER="Kitronic"'
            -DAD_P_MIN_DELTA_BAR=6.0
            -DAD_TT_MAX_MS=500
            -DAD_VBUS_MIN_V=12.0
            -DAD_I_COIL_OPEN_MAX_mA=80
            -DAD_I_COIL_SHORT_MIN_mA=3000

lib_deps =
  adafruit/Adafruit ADS1X15@^2.6.0
  adafruit/Adafruit INA219@^1.2.3
  bblanchon/ArduinoJson @ ^7.4.2
  jandrassy/EthernetENC@^2.0.5
  olikraus/U8g2 @ ^2.36.5